name: Add contributor

on:
  push:
    branches:
      - "master"

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - uses: akhilmhdh/contributors-readme-action@v2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
